test-percentage: 20
cv-folds: 10
paths:
  images:
    w2v:
      root: images/w2v
  slots-intents-module: vendor/slots_intents/intents_slots
  joint-nlu-module: 
    src: vendor/Joint-NLU/src
  models:
    root: models
    joint-nlu: models/joint-nlu
    slots-intents:
      name: model.h5
      path: models/slots-intents
    w2v: models/w2v
    ar100w2v: ~/models/ArModel100w2v.txt
  datasets:
    root: dataset
    annotations: dataset/annotations
    flawy-denormalized: dataset/denormalized-annotations/flawy.json
    nice-denormalized: dataset/denormalized-annotations/nice.json
    iot-commands:
      data: dataset/iot-commands/data.txt
      annotations: dataset/annotations/iot-commands
    not-commands:
      data: dataset/not-commands/data-sorokin.txt
      annotations: dataset/annotations/not-commands
    parlai:
      data: dataset/parlai/data.txt
    vw:
      data: dataset/vw/data.txt
      train: dataset/vw/train.txt
      test: dataset/vw/test.txt
    pytext:
      data: dataset/pytext/data.tsv
      data-extended: dataset/pytext/data-extended.tsv
      train: dataset/pytext/train.tsv
      train-extended: dataset/pytext/train-extended.tsv
      test: dataset/pytext/test.json
      test-extended: dataset/pytext/test-extended.json
      validate: dataset/pytext/validate.tsv
      validate-extended: dataset/pytext/validate-extended.tsv
    snips-nlu:
      data: dataset/snips-nlu/data.json
      train: dataset/snips-nlu/train.tsv
      test: dataset/snips-nlu/test.json
    slots-intents:
      data: dataset/slots-intents/data.csv
      train: dataset/slots-intents/train.csv
      test: dataset/slots-intents/test.json
      validate: dataset/slots-intents/validate.csv
      info: dataset/slots-intents/dataset_info
    joint-nlu:
      root: dataset/joint-nlu
      data: dataset/joint-nlu/data
      train: dataset/joint-nlu/train
      test: dataset/joint-nlu/test
      validate: dataset/joint-nlu/valid
      vocabulary: dataset/joint-nlu
      filenames:
        data:
          labels: label
          texts: seq.in
          slots: seq.out
        vocabulary:
          labels: intent_vocab
          texts: in_vocab
          slots: slot_vocab
    w2v:
      root: dataset/w2v
  etc:
    pytext:
      model: models/pytext/model.caffe2.predictor
      model-extended: /tmp/model.caffe2.predictor #models/pytext/model-bilstm-without-pretrained-embeddings.caffe2.predictor
      model-config: vendor/pytext/bilstm.json
      model-config-extended: vendor/pytext/bilstm-without-pretrained-embeddings.json
    slots-intents:
      w2v: vendor/word-vectors/poincare.txt